# -*- coding: utf-8 -*-
"""poisson.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1seLuX9_dumFxFxXQj6lSau6IRGJDT8Fb
"""

from scipy.stats import poisson

"""Média de acidentes de carro por dia = 2"""

# Qual a probabilidade de ocorrerem 3 acidentes no dia
float(poisson.pmf(3, 2))

# Qual a probabilidade de ocorrerem menos de 3 acidentes no dia
float(poisson.cdf(3, 2))

# Qual a probabilidade de ocorrerem mais de 3 acidentes no dia
float(poisson.sf(3, 2))